mod text_align;
pub use text_align::*;
mod text_decoration;
pub use text_decoration::*;
mod text_indent;
pub use text_indent::*;
mod text_decoration_skip_ink;
pub use text_decoration_skip_ink::*;
mod text_overflow;
pub use text_overflow::*;
mod text_size_adjust;
pub use text_size_adjust::*;
mod text_transform;
pub use text_transform::*;
mod text_wrap;
pub use text_wrap::*;
mod webkit_text_decoration;
pub use webkit_text_decoration::*;
mod webkit_text_size_adjust;
pub use webkit_text_size_adjust::*;
