[package]
name = "fixtures"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
granola = { path = "../../crates/granola" }
seahash = "4.1.0"

[build-dependencies]
granola-scanner = { path = "../../crates/granola-scanner" }

[lints]
workspace = true
